import { v4 as uuid } from "uuid";
//pics
import ac1 from "../assets/ac1.jpg";
import ac2 from "../assets/ac2.jpg";
import acv from "../assets/acv.jpg";
import gow from "../assets/gow.jpg";
import h1 from "../assets/h1.jpg";
import forza5 from "../assets/forza5.jpg";
import div2 from "../assets/div2.jpg";
import rssiege from "../assets/rssiege.jpg";
import cyber from "../assets/cyber.jpg";
import fm from "../assets/fm.jpg";
import avatar1 from "../assets/avatar1.jpg";
import prince1 from "../assets/prince1.jpg";
import forza1 from "../assets/forza1.jpg";
import diablo1 from "../assets/diablo1.jpg";
import gollum1 from "../assets/gollum1.jpg";
import sw1 from "../assets/sw1.jpg";
import redfall1 from "../assets/redfall1.jpg";
import sf1 from "../assets/sf1.jpg";
import bf1 from "../assets/bf.jpg";
import fifa1 from "../assets/fifa.jpg";
import di1 from "../assets/di1.jpg";
import fc2 from "../assets/fc2.jpg";
import f1 from "../assets/f1jpg.jpg";
import aliens from "../assets/aliens.jpg";
import pd3 from "../assets/pd3.jpg";
import hp1 from "../assets/hp1.jpg";
import ch1 from "../assets/ch1.jpg";
import wwe1 from "../assets/wwe1.jpg";
import armorcore from "../assets/armorcore.jpg";
import acm from "../assets/acm.jpg";
import returnal from "../assets/returnal1.jpg";
import ds from "../assets/ds.jpg";
import ah1 from "../assets/ah1.jpg";
import mc1 from "../assets/mc1.jpg";
import re4 from "../assets/re4.jpg";
import bb1 from "../assets/bb1.jpg";
import ed1 from "../assets/ed1.jpg";
import spider from "../assets/spider.jpg";
import er1 from "../assets/er1.jpg";
import nba from "../assets/nba.jpg";
import ready from "../assets/ready.jpg";
import rdr1 from "../assets/rdr1.jpg";
import gta from "../assets/gta.jpg";
import starfield from "../assets/starfield.jpg";
import ja1 from "../assets/ja1.jpg";

import {
  CategoriesType,
  FaqType,
  MyAccountType,
  MyArticleType,
  MyGameStatsType,
  MyGameType,
  PrivacyType,
  TermsType,
} from "../types/types";
//category
import bg1 from "../assets/ac2.jpg";
import bg2 from "../assets/bg2.jpg";
import bg3 from "../assets/bg3.jpg";
import bg4 from "../assets/bg4.jpg";
import categoryAction from "../assets/category-icon1.webp";
import categoryStrategy from "../assets/category-icon17.webp";
import categoryHorror from "../assets/category-icon4.webp";
import categorySport from "../assets/category-icon16.webp";

export const accountData: MyAccountType = {
  id: uuid(),
  ign: "Maroš",
  accountCreated: "7.3.2023",
  email: "gamer@gamer.com",
  gamesOwned: 3,
  hoursPlayed: 7,
  lastPlayed: "Mad Math",
};

export const articlesData: MyArticleType[] = [
  {
    id: uuid(),
    picture: [starfield],
    genre: "action",
    publisher: "Overkill",
    title: "Starfield",
    releaseDate: "6th september, 2023",
    text: `Starfield is the first new universe in over 25 years from Bethesda Game Studios, the award-winning creators of The Elder Scrolls V: Skyrim and Fallout 4. In this next generation role-playing game set amongst the stars, create any character you want and explore with unparalleled freedom as you embark on an epic journey to answer humanity’s greatest mystery.`,
    video: "https://www.youtube.com/embed/kfYEiTdsyas",
  },
  {
    id: uuid(),
    picture: [pd3],
    genre: "action",
    publisher: "Overkill",
    title: "Pyday  3",
    releaseDate: "21st september, 2023",
    text: `PAYDAY 3 is the much anticipated sequel to one of the most popular co-op shooters ever. Since its release, PAYDAY-players have been reveling in the thrill of a perfectly planned and executed heist. That’s what makes PAYDAY a high-octane, co-op FPS experience without equal. Step out of retirement back into the life of crime in the shoes of the Payday Gang, the envy of their peers and the nightmare of law-enforcement wherever they go.`,
    video: "https://www.youtube.com/embed/dc5gw3ctb0o",
  },
  {
    id: uuid(),
    picture: [forza1],
    genre: "sport",
    publisher: "Microsoft",
    title: "Forza Motorsport (2023)",
    releaseDate: "10th october, 2023",
    text: `The authors say that the campaign will evolve, and new cars and tracks that will come into the game after the release will automatically expand it.
      You will level up in the campaign, improve your cars and dominate the tracks. At the same time, it will be up to you how deeply you will go into it and modify and replace individual parts in the car, or whether you will leave it to the automatic. It works the same way when driving, where forza has always had a wide range of simplification settings. Finally, it now adds a mode for blind players.`,
    video: "https://www.youtube.com/embed/em4gv1Ietko",
  },
  {
    id: uuid(),
    picture: [armorcore],
    genre: "action",
    publisher: "Bandai Namco",
    title: "Armored Core VI: Fires of Rubicon",
    releaseDate: "25st august, 2023",
    text: `Combining FromSoftware’s longstanding expertise in mech games with their signature action gameplay, ARMORED CORE VI FIRES OF RUBICON brings a brand-new action experience to the series. Dynamic, Omni-directional Battles Players will pilot their mech in fast-paced, omni-directional battles, taking advantage of massive stages and their mech’s mobility on land and in the air to ensure victory.`,
    video: "https://www.youtube.com/embed/SlSfr6Wa5sc",
  },
  {
    id: uuid(),
    picture: [acm, ac1, ac2],
    genre: "action",
    publisher: "Ubisoft",
    title: "Assassin's Creed Mirage",
    releaseDate: "12th october, 2023",
    text: `Ubisoft has finished Mirage, new addition to AC family. We will follow the character of Basim, who we saw in Valhalla and who we will now see in his youth, as he searches for his way to freedom, but in the end he finds something else. Of the technical things, stealth will be improved, which will be the basis of the game, but at the same time, parkour, or the AI of enemies, will also be improved. At the same time, the killing animations have been improved and the arsenal will be expanded. In particular, you will get news like smoke bombs, you will have throwing knives and other accessories.`,
    video: "https://www.youtube.com/embed/9hjico7nYvo",
  },
  {
    id: uuid(),
    picture: [ja1],
    genre: "horror",
    publisher: "THQ",
    title: "Jagged Alliance 3",
    releaseDate: "14th july, 2023",
    text: `Grand Chien, a nation of rich natural resources and deep political divides, is thrown into chaos when the elected president goes missing and a paramilitary force known as “The Legion” seizes control of the countryside. Now, the President’s family has pulled together all their resources, including an arrangement with the powerful Adonis corporation, to hire a group of skilled mercenaries tasked with finding the President and bringing order back to the country.`,
    video: "https://www.youtube.com/embed/5t09aNdl18c",
  },
  {
    id: uuid(),
    picture: [avatar1],
    genre: "action",
    publisher: "Ubisoft",
    title: "Avatar: Frontiers of Pandora",
    releaseDate: "7th december, 2023",
    text: `Ubisoft has finally presented us with its upcoming game based on the Avatar film series. It will be called Avatar: Frontiers of Pandora and mainly its technological side was shown to us in the first video, although it is still questionable what the gameplay will be. The game is being worked on by the studio Massive, which has The Division games and is also working on a new Star Wars game.
      The game will run on the Snowdrop engine and will take us beyond the western border, to the hitherto unexplored places of the planet Pandora.`,
    video: "https://www.youtube.com/embed/Axmg1E4HrVE",
  },
  {
    id: uuid(),
    picture: [prince1],
    genre: "action",
    publisher: "Ubisoft",
    title: "Prince of Persia: The Lost Crown",
    releaseDate: "18th january, 2024",
    text: `Ubisoft brought the already announced return of Prince of Persia to its presentation. It will be in the form of a jumper and will arrive on January 18, 2024. It will be a new saga in the series, in which we will try to save the kidnapped Prince Hasan.
      Although the game will be in a jumping version from a side view, the world will be semi-open and will constantly reveal more of its secrets.`,
    video: "https://www.youtube.com/embed/MmX7a_e65uU",
  },
];

export const FAQdata: FaqType[] = [
  {
    id: uuid(),
    question: "What is Gamer?",
    answer:
      "Gamer is modern client for every passionated gamer with possibility of playing games and reading about them.",
  },
  {
    id: uuid(),
    question: "Is Gamer free app?",
    answer: "Yes, Gamer app is free to download.",
  },
  {
    id: uuid(),
    question: "How can i report a bug?",
    answer:
      "There is section called send feedback, where you can report a bug.",
  },
];

export const storeProductsData: MyGameType[] = [
  {
    id: uuid(),
    picture: diablo1,
    genre: "action",
    publisher: "Blizzard",
    title: "Diablo IV",
    price: 75.55,
    oldPrice: 75.55,
    quantity: 7,
    currencyFormat: "€",
    platform: ["PC", "Xbox", "PS"],
    text: `One of the most anticipated games of not only this, but the last few years, has finally been released. It was preceded by public testing, a big promotion with a lot of video trailers, themed hardware and strong speeches about what a bomb awaits us. Blizzard has left nothing to chance because it knows that Diablo IV will be its cash cow for a long time. Maybe until the release of the next part. Be that as it may, it's played well and the hellhound will find a lot of fans this time as well.`,
    video: "https://www.youtube.com/embed/HukrLKMCz1I",
    status: "trending",
    discount: false,
  },
  {
    id: uuid(),
    picture: gollum1,
    genre: "adventure",
    publisher: "Daedalic Ent.",
    title: "LOTR: Gollum",
    price: 68.65,
    oldPrice: 75.55,
    quantity: 10,
    currencyFormat: "€",
    platform: ["PC", "Xbox", "PS"],
    text: `You can only imagine, one of the most famous fantasy worlds lives on our screens after a long time. This time, we will not rush to the Mountain of Destiny in the clutches of the good ones. Let's put ourselves in the shoes of schizophrenic Gollum (or Gollum/Smeágol if you prefer) and find out what happened to his poor life when he lost his "sweetheart". Different game genres by excellent storytellers. What could possibly go wrong?`,
    video: "https://www.youtube.com/embed/kJn2AjYOIJA",
    status: "none",
    discount: true,
  },
  {
    id: uuid(),
    picture: sw1,
    genre: "action",
    publisher: "EA",
    title: "Star Wars: Jedi Survivor",
    price: 54.99,
    oldPrice: 75.55,
    quantity: 11,
    currencyFormat: "€",
    platform: ["PC", "Xbox", "PS"],
    text: `Discover new planets and revisit familiar frontiers in the Star Wars galaxy, each with unique biomes, challenges, and enemies. Master new skills, equipment, and abilities as you traverse grandiose landscapes and take roads less traveled; players who adventure beyond the horizon will be rewarded handsomely. `,
    video: "https://www.youtube.com/embed/bmj3ty-Wt48",
    status: "trending",
    discount: true,
  },
  {
    id: uuid(),
    picture: redfall1,
    genre: "horror",
    publisher: "Bethesda",
    title: "Redfall",
    price: 35.85,
    oldPrice: 38.32,
    quantity: 8,
    currencyFormat: "€",
    text: `Redfall is an open-world, co-op FPS from Arkane Austin, the award-winning team behind Prey and Dishonored. Continuing Arkane’s legacy of carefully crafted worlds and immersive sims, Redfall brings the studio’s signature gameplay to this story-driven action shooter. The island town of Redfall, Massachusetts, is under siege by a legion of vampires who have blocked out the sun and cut the citizens off from the outside world. Explore the open world and immerse yourself in a deep story campaign as you unravel the mystery behind the vampires’ appearance. Ally with a handful of survivors against the creatures threatening to bleed the town dry.`,
    platform: ["PC", "Xbox", "PS"],
    video: "https://www.youtube.com/embed/8cCFN77wtHY",
    status: "none",
    discount: true,
  },
  {
    id: uuid(),
    picture: sf1,
    genre: "action",
    publisher: "Capcom",
    title: "Street Fighter 6",
    price: 44.85,
    oldPrice: 44.85,
    quantity: 3,
    currencyFormat: "€",
    platform: ["Xbox", "PS"],
    text: `Here comes Capcom’s newest challenger! Street Fighter™ 6 launches worldwide on June 2nd, 2023 and represents the next evolution of the Street Fighter™ series! Street Fighter 6 spans three distinct game modes, including World Tour, Fighting Ground and Battle Hub.`,
    video: "https://www.youtube.com/embed/zMm60rQ9p30",
    status: "none",
    discount: false,
  },
  {
    id: uuid(),
    picture: bf1,
    genre: "action",
    publisher: "Dice",
    title: "Battlefield 2042",
    price: 50.85,
    oldPrice: 50.85,
    quantity: 9,
    currencyFormat: "€",
    platform: ["PC", "Xbox", "PS"],
    text: `Battlefield™ 2042 is a first-person shooter that marks the return to the iconic all-out warfare of the franchise. Utilize a cutting-edge arsenal in immersive multiplayer battles on maps set in both open battlegrounds and close-quarters maps. Choose your class, rally your squad, and fight through the world of 2042 as well as Battlefield's past.`,
    video: "https://www.youtube.com/embed/ASzOzrB-a9E",
    status: "trending",
    discount: false,
  },
  {
    id: uuid(),
    picture: fifa1,
    genre: "sport",
    publisher: "EA",
    title: "Fifa 23",
    price: 25.05,
    oldPrice: 50.85,
    quantity: 5,
    currencyFormat: "€",
    platform: ["PC", "Xbox", "PS"],
    text: `EA SPORTS™ FIFA 23 brings the world's most popular game to the pitch between the men's and women's FIFA World Cup™ tournaments, expanded with the women's clubs and new ways to play your favorite modes.
    Advances in HyperMotion2 technology with PS5 bring even more football action and realism to the pitch. With twice the real-time motion capture, football animations are now played more realistically than ever before.`,
    video: "https://www.youtube.com/embed/0tIW1X2dv0c",
    status: "bestseller",
    discount: true,
  },
  {
    id: uuid(),
    picture: fc2,
    genre: "action",
    publisher: "Ubisoft",
    title: "Far Cry 6",
    price: 32.75,
    oldPrice: 45.45,
    quantity: 2,
    currencyFormat: "€",
    platform: ["PC", "Xbox", "PS"],
    text: `Far Cry 6 is a 2021 action first-person shooter developed by Ubisoft Toronto and published by Ubisoft. It is the sixth installment in the Far Cry game series, released on October 7, 2021 for Amazon Luna, Microsoft Windows, PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S and Stadia platforms`,
    video: "https://www.youtube.com/embed/qjSM3Lp7EhI",
    status: "bestseller",
    discount: true,
  },
  // odtial zmazat
  {
    id: uuid(),
    picture: f1,
    genre: "sport",
    publisher: "EA",
    title: "F1 2023",
    price: 75.55,
    oldPrice: 75.55,
    quantity: 5,
    currencyFormat: "€",
    platform: ["PC", "Xbox", "PS"],
    text: `Be the last to brake in EA SPORTS™ F1® 23, the official video game of the 2023 FIA Formula One World Championship™. This game includes optional in-game purchases of virtual currency that can be used to acquire virtual in-game items.`,
    video: "https://www.youtube.com/embed/wHNgoRCWqTg",
    status: "trending",
    discount: false,
  },
  {
    id: uuid(),
    picture: aliens,
    genre: "horror",
    publisher: "Tindalos",
    title: "Aliens: Dark Descent",
    price: 75.55,
    oldPrice: 75.55,
    quantity: 5,
    currencyFormat: "€",
    platform: ["PC", "Xbox"],
    text: `In Aliens: Dark Descent, command a squad of hardened Colonial Marines to stop a terrifying Xenomorph outbreak on Planet Lethe. Lead your soldiers in real-time combat against iconic Xenomorphs, rogue operatives from the insatiable Weyland-Yutani Corporation, and a host of horrifying creatures new to the Alien franchise. You are the commander. They are your weapon.`,
    video: "https://www.youtube.com/embed/5ZNnZojcFJA",
    status: "bestseller",
    discount: false,
  },
  {
    id: uuid(),
    picture: hp1,
    genre: "RPG",
    publisher: "Avalanche",
    title: "Hogwarts Legacy Deluxe Edition",
    price: 68.65,
    oldPrice: 75.55,
    quantity: 10,
    currencyFormat: "€",
    platform: ["PC", "Xbox"],
    text: `Hogwarts Legacy is an open-world action RPG set in the world first introduced in the Harry Potter books. Embark on a journey through familiar and new locations as you explore and discover magical beasts, customize your character and craft potions, master spell casting, upgrade talents and become the wizard you want to be. Experience Hogwarts in the 1800s.`,
    video: "https://www.youtube.com/embed/1O6Qstncpnc",
    status: "trending",
    discount: true,
  },
  {
    id: uuid(),
    picture: ch1,
    genre: "strategy",
    publisher: "Relic",
    title: "Company of Heroes 3",
    price: 54.99,
    oldPrice: 58.45,
    quantity: 11,
    currencyFormat: "€",
    platform: ["PC"],
    text: `Company of Heroes 3 for PC is a real time strategy game, the sequel to Company of Heroes 2 and is set in the WWII theatres of Italy and North Africa. You can play as Allied forces in Italy (the Allied invasion of Italy peninsula ensured its docility as WWII amped up – this historical (and highly sensible) move is rarely featured in WWII gaming) or as Axis forces in North Africa.`,
    video: "https://www.youtube.com/embed/F0nWPG_cFqY",
    status: "none",
    discount: true,
  },
  {
    id: uuid(),
    picture: wwe1,
    genre: "sport",
    publisher: "Visual Concepts",
    title: "WWE 2k23",
    price: 35.85,
    oldPrice: 40.89,
    quantity: 8,
    currencyFormat: "€",
    text: `Expanded features, gorgeous graphics, and the ultimate WWE experience. Hit the ring with a deep roster of WWE Superstars and Legends including Roman Reigns, "American Nightmare" Cody Rhodes, Ronda Rousey, Brock Lesnar, "Stone Cold" Steve Austin and more!2K SHOWCASE: INTERACTIVE SPORTS DOCUMENTARYPlay through the key moments and toughest opponents of John Cena’s storied 20-year WWE career.`,
    platform: ["PC", "Xbox"],
    video: "https://www.youtube.com/embed/4cuNm8acf64",
    status: "none",
    discount: true,
  },
  {
    id: uuid(),
    picture: ah1,
    genre: "action",
    publisher: "Mundfish",
    title: "Atomic Heart",
    price: 44.85,
    oldPrice: 75.55,
    quantity: 4,
    currencyFormat: "€",
    platform: ["Xbox One", "PC"],
    text: `Welcome to a utopian world of wonders and perfection, in which humans live in harmony with their loyal and fervent robots. Well, that's how it used to be. With the launch of the latest robot-control system mere days away, only a tragic accident or a global conspiracy could disrupt it… The unstoppable course of technology along with secret experiments have brought rise to mutant creatures, terrifying machines and superpowered robots`,
    video: "https://www.youtube.com/embed/ZXSi4EcxnuY",
    status: "bestseller",
    discount: true,
  },
  {
    id: uuid(),
    picture: returnal,
    genre: "horror",
    publisher: "Climax",
    title: "Returnal",
    price: 50.85,
    oldPrice: 55.55,
    quantity: 8,
    currencyFormat: "€",
    platform: ["PS"],
    text: `Break the cycle as this award-winning third-person shooter brings bullet hell action to PC. Selene’s roguelike odyssey arrives with a suite of arresting graphical and performance-based enhancements to ensure an unforgettable journey. This includes the full Returnal™ experience, complete with Suspend Cycle, Photo and Co-op Modes, as well as the Tower of Sisyphus included from day one.`,
    video: "https://www.youtube.com/embed/Jv4BjWoB-NA",
    status: "trending",
    discount: true,
  },
  {
    id: uuid(),
    picture: ds,
    genre: "horror",
    publisher: "Motive",
    title: "Dead Space",
    price: 25.05,
    oldPrice: 42.55,
    quantity: 2,
    currencyFormat: "€",
    platform: ["PC", "Xbox"],
    text: `Dead Space for PC is a remake of the 2008 original horror survival video game of the same name, which was followed by sequels: Dead Space 2 (2011) and Dead Space 3 (2013) and a spin-off ‘universe’ called Dead Space Franchise which included more games, films and graphic novels/ comic books. About the Game Set in the year 2508, a dystopian space age future in which the Earth’s resources have been plundered.`,
    video: "https://www.youtube.com/embed/cTDJNZ9cK1w",
    status: "bestseller",
    discount: true,
  },
  {
    id: uuid(),
    picture: mc1,
    genre: "action",
    publisher: "NetherRealm",
    title: "Mortal Combat 1",
    price: 32.75,
    oldPrice: 37.55,
    quantity: 8,
    currencyFormat: "€",
    platform: ["PC", "Xbox", "PS"],
    text: `t’s In Our Blood! Discover a reborn Mortal Kombat Universe created by the Fire God Liu Kang. Mortal Kombat 1 ushers in a new era of the iconic franchise with a new fighting system, game modes, and fatalities!`,
    video: "https://www.youtube.com/embed/UZ6eFEjFfJ0",
    status: "trending",
    discount: true,
  },
  {
    id: uuid(),
    picture: re4,
    genre: "horror",
    publisher: "Capcom",
    title: "Resident Evil 4",
    price: 25.55,
    oldPrice: 25.55,
    quantity: 7,
    currencyFormat: "€",
    platform: ["PC", "Xbox"],
    text: `Survival is just the beginning. Six years have passed since the biological disaster in Raccoon City. Agent Leon S. Kennedy, one of the survivors of the incident, has been sent to rescue the president's kidnapped daughter. He tracks her to a secluded European village, where there is something terribly wrong with the locals. And the curtain rises on this story of daring rescue and grueling horror where life and death, terror and catharsis intersect. `,
    video: "https://www.youtube.com/embed/Id2EaldBaWw",
    status: "bestseller",
    discount: false,
  },
  {
    id: uuid(),
    picture: di1,
    genre: "adventure",
    publisher: "Deep Silver",
    title: "Dead Island 2",
    price: 68.65,
    oldPrice: 68.65,
    quantity: 10,
    currencyFormat: "€",
    platform: ["PC", "Xbox"],
    text: `The much-loved zombie saga is back with a unique formula of horror, dark humor and over the top zombie-slaying, spanning an epic pulp adventure. Dead Island 2 is a thrilling First-Person Action RPG, stylish, vibrant and flooded with zombie infection. Explore an iconic, gore-drenched Los Angeles. Meet larger-than-life characters. Slay countless foes in exquisitely bloody detail. And evolve to become the ultimate Zombie Slayer! `,
    video: "https://www.youtube.com/embed/u6Qypoo0a8w",
    status: "none",
    discount: false,
  },
  {
    id: uuid(),
    picture: bb1,
    genre: "sport",
    publisher: "Cyanide",
    title: "Blood Bowl 3",
    price: 54.99,
    oldPrice: 65.49,
    quantity: 11,
    currencyFormat: "€",
    platform: ["PC"],
    text: `Strap on your boots, don your helmet, adjust your shoulder guards and chest plate… and slip a sharpened dagger into your belt (discreetly). Wars are no longer fought in the Old World since the populace decided to resolve their differences through a sport dedicated to the god Nuffle: Blood Bowl. However, just as much blood is shed in this sport as on the battlefields it replaced. Murder, mutilation, cheating, corruption, sorcery and even divine intervention are all fair. `,
    video: "https://www.youtube.com/embed/ZVV6jcjdrEI",
    status: "none",
    discount: true,
  },
  {
    id: uuid(),
    picture: ed1,
    genre: "horror",
    publisher: "Saber",
    title: "Evil Dead: The Game",
    price: 5.85,
    oldPrice: 7.65,
    quantity: 8,
    currencyFormat: "€",
    text: `The ultimate Evil Dead multiplayer experience is here… and it’s groovy! Step into the shoes of Ash Williams or his friends from the iconic Evil Dead franchise and work together in a game loaded with over-the-top co-op and PVP multiplayer action! Play as a team of four survivors, exploring, looting, managing your fear, and finding key items to seal the breach between worlds in a game inspired by all three original Evil Dead films`,
    platform: ["PC", "Xbox", "PS"],
    video: "https://www.youtube.com/embed/LiZqKiamYSs",
    status: "none",
    discount: true,
  },
  {
    id: uuid(),
    picture: spider,
    genre: "action",
    publisher: "Insomnia",
    title: "Spider Man: Remastered",
    price: 44.85,
    oldPrice: 44.85,
    quantity: 3,
    currencyFormat: "€",
    platform: ["PC", "PS"],
    text: `Marvel's Spider-Man Remastered for PC is a refreshed version of the action adventure game from 2018. Featuring third person play, you take on the character of web-lord, Spider-Man, dealing with Peter Parker’s personal life as well as battling super-human villain Mister Negative – a villain’s name if there ever was one! – in his bid to take over New York’s underworld. About the Game Mister Negative plans to achieve his aims by unleashing a deadly virus on the city.`,
    video: "https://www.youtube.com/embed/1E051WtpyWg",
    status: "bestseller",
    discount: false,
  },
  {
    id: uuid(),
    picture: er1,
    genre: "RPG",
    publisher: "Bandai Namco",
    title: "Elden Ring",
    price: 50.85,
    oldPrice: 52.75,
    quantity: 9,
    currencyFormat: "€",
    platform: ["PC", "Xbox", "PS"],
    text: `Elden Ring for PC is an action role playing game (ARPG) written by superstars George R R Martin (the author of the Song of Ice and Fire series of books which begat television show Game of Thrones) and Hidetaka Miyazake (who is famed for many popular video games: from the Souls series, to Bloodborne, to Sekiro amongst many others). About the Game The Elden Ring has been destroyed and its shards have scattered throughout the lands.`,
    video: "https://www.youtube.com/embed/E3Huy2cdih0",
    status: "bestseller",
    discount: true,
  },
  {
    id: uuid(),
    picture: nba,
    genre: "sport",
    publisher: "Visual Concepts",
    title: "NBA 2K23",
    price: 25.05,
    oldPrice: 52.75,
    quantity: 5,
    currencyFormat: "€",
    platform: ["PC", "Xbox", "PS"],
    text: `NBA 2K23 for PC is the latest in the long-running NBA game series, starring real life basketball stars and championships. About the Game Previous games received complaints that open shots tended to nearly always succeed, and the games developers have taken this to heart, with contested shots now more challenging to pull off. There are also 20 different shot metre options to use – although only five are unlocked when the game begins.`,
    video: "https://www.youtube.com/embed/RxLS5Tgo9YM",
    status: "none",
    discount: true,
  },
  {
    id: uuid(),
    picture: fm,
    genre: "sport",
    publisher: "Sega",
    title: "Football Manager 2023",
    price: 32.75,
    oldPrice: 45.45,
    quantity: 2,
    currencyFormat: "€",
    platform: ["PC"],
    text: `Football Manager 2023 for PC is, as it looks, a football management simulation game, fully licensed by UEFA (down to club competitions for the first time), and – also for the first time – with a nod to the woman’s game, which is down to be included in a later version of the game, the relevant agreements by all parties having been made.`,
    video: "https://www.youtube.com/embed/ISJxT7VLzYg",
    status: "trending",
    discount: true,
  },
  {
    id: uuid(),
    picture: ready,
    genre: "action",
    publisher: "Void Interactive",
    title: "Ready or Not",
    price: 39.99,
    oldPrice: 39.99,
    quantity: 5,
    currencyFormat: "€",
    platform: ["PC"],
    text: `Ready or Not is an intense, tactical, first-person shooter that depicts a modern-day world in which SWAT police units are called to defuse hostile and confronting situations. Please remember that the Beta build is still an incomplete version of the game. It will still have bugs and quirks, and will require lots of additional content before it is ready for full release. `,
    video: "https://www.youtube.com/embed/IjscQ0HtaCg",
    status: "bestseller",
    discount: false,
  },
  {
    id: uuid(),
    picture: cyber,
    genre: "RPG",
    publisher: "Cd Project",
    title: "Cyberpunk 2077",
    price: 68.65,
    oldPrice: 68.65,
    quantity: 10,
    currencyFormat: "€",
    platform: ["PC", "Xbox", "PS"],
    text: `Cyberpunk 2077 for PC is a first-person shooter game, but one with a difference. Set in a dystopian Free State of California, the rules of the nation and the state no longer apply. Instead, playing as a mercenary named V, the player must work their way around the city, attaining their goals and battling enemies as they go. About the Game Seven years in the making, Cyberpunk 2077 looks to be living up to all the hype generated by its introduction`,
    video: "https://www.youtube.com/embed/qIcTM8WXFjk",
    status: "bestseller",
    discount: false,
  },
  {
    id: uuid(),
    picture: rdr1,
    genre: "action",
    publisher: "Rockstar",
    title: "Red Dead Redemption 2",
    price: 54.99,
    oldPrice: 68.65,
    quantity: 11,
    currencyFormat: "€",
    platform: ["PC", "Xbox", "PS"],
    text: `Red Dead Redemption 2 for PC is an action adventure, open world game in which the player can roam freely with some elements playing out in third person, others in first person play modes. The player can commit crimes, but must then be prepared for law enforcement to hunt them down, ready to bring to bear the full weight of the law on the miscreant!  `,
    video: "https://www.youtube.com/embed/eaW0tYpxyp0",
    status: "trending",
    discount: true,
  },
  {
    id: uuid(),
    picture: rssiege,
    genre: "action",
    publisher: "Ubisoft",
    title: "Rainbow Six: Siege",
    price: 35.85,
    oldPrice: 35.85,
    quantity: 8,
    currencyFormat: "€",
    text: `Rainbow Six Siege for PC is an online tactical shooter game. There is a strong emphasis on environmental destruction and cooperation between players, with each player assuming control of a playing character to defend or attack in each different scenario. These include hostage rescue, bomb defusing, and capturing or defending a control point.`,
    platform: ["PC", "Xbox", "PS"],
    video: "https://www.youtube.com/embed/jQeh4BJxfMg",
    status: "none",
    discount: false,
  },
  {
    id: uuid(),
    picture: gta,
    genre: "action",
    publisher: "Rockstar",
    title: "GTA 5",
    price: 44.85,
    oldPrice: 48.88,
    quantity: 3,
    currencyFormat: "€",
    platform: ["PC", "Xbox", "PS"],
    text: `HGrand Theft Auto V for PC is an action adventure game, the fifth in the GTA series. As with the other games in the series, you score points by committing crimes. The game alternates between third-person narrative and play and first-person play, and you play as three criminals trying to avoid a determined government agency and committing heists.`,
    video: "https://www.youtube.com/embed/QkkoHAzjnUs",
    status: "none",
    discount: true,
  },
  {
    id: uuid(),
    picture: acv,
    genre: "action",
    publisher: "Ubisoft",
    title: "Assassins's Creed: Valhalla",
    price: 50.85,
    oldPrice: 50.85,
    quantity: 9,
    currencyFormat: "€",
    platform: ["PC", "Xbox", "PS"],
    text: `Assassin’s Creed Valhalla for PC is the 12th instalment of the Assassin’s Creed games, and this one takes place in the 9th century (beginning in 873AD) carrying you across Europe as you move your clan from a seriously overcrowded and war torn Norway to England, a green land of peace, prosperity and fertile fields in which to raise your crops. The UK might have a reputation as being a chilly and rainy place, but compared to near arctic desolation, it is not.`,
    video: "https://www.youtube.com/embed/ssrNcwxALS4",
    status: "trending",
    discount: false,
  },
  {
    id: uuid(),
    picture: gow,
    genre: "action",
    publisher: "Santa Monica",
    title: "God of War",
    price: 25.05,
    oldPrice: 37.79,
    quantity: 5,
    currencyFormat: "€",
    platform: ["PC", "Xbox", "PS"],
    text: `God of War for PC was teased for months, from about halfway through 2021 until the developers finally put players out of their misery and confirmed the PC release in January 2022! It is the PC-friendly version of the 2018 Gods of War, which was initially only available on PlayStation. The game allows PC gamers to enjoy the intense Norse God action-adventure game.`,
    video: "https://www.youtube.com/embed/K0u_kAWLJOA",
    status: "bestseller",
    discount: true,
  },
  {
    id: uuid(),
    picture: h1,
    genre: "action",
    publisher: "Guerilla",
    title: "Horizon Zero Dawn",
    price: 32.75,
    oldPrice: 37.79,
    quantity: 2,
    currencyFormat: "€",
    platform: ["PC", "PS"],
    text: `Horizon Zero Dawn for PC is an action role playing game in which you control Aloy, a rare human survivor in the 31st century dystopian landscape. Humans may be rare, and access to technology is limited, but there is a large population of unfriendly robotic creatures (who were originally created by Big Tech who then lost control of them).`,
    video: "https://www.youtube.com/embed/u4-FCsiF5x4",
    status: "bestseller",
    discount: true,
  },
  {
    id: uuid(),
    picture: forza5,
    genre: "sport",
    publisher: "Microsoft",
    title: "Forza 5",
    price: 75.55,
    oldPrice: 75.55,
    quantity: 5,
    currencyFormat: "€",
    platform: ["Xbox"],
    text: `Forza Horizon 5 for PC is a racing simulation game set in a number of beautiful locations around Mexico. It is the fifth game in the Forza Horizon series, and the twelfth main game from the overall Forza franchise. About the Game In this game, you can explore a truly massive open world map, as much as fifty percent larger than Forza Horizon 4’s not inconsiderable map.`,
    video: "https://www.youtube.com/embed/Rv7xLt5yNsM",
    status: "trending",
    discount: false,
  },
  {
    id: uuid(),
    picture: div2,
    genre: "RPG",
    publisher: "Ubisoft",
    title: "The Division 2",
    price: 68.65,
    oldPrice: 75.55,
    quantity: 10,
    currencyFormat: "€",
    platform: ["PC", "Xbox", "PS"],
    text: `Tom Clancy’s The Division 2 for PC follows on from the first game of the name. The first game dealt with the aftermath of a worldwide pandemic of weaponised smallpox (known as Green Poison) released in New York by an environmental terrorist. In the final days before the pandemic devastated society, the US government activated The Division – a domestic sleeper agency properly known as Strategic Homeland Division or SHD.`,
    video: "https://www.youtube.com/embed/sli7AbX2bEk",
    status: "none",
    discount: true,
  },
];

export const myLibraryData: MyGameType[] = [];

export const purchaseData: MyGameStatsType[] = [
  {
    id: uuid(),
    month: "January",
    gamesPurchased: 1,
  },
  {
    id: uuid(),
    month: "February",
    gamesPurchased: 2,
  },
  {
    id: uuid(),
    month: "March",
    gamesPurchased: 4,
  },
  {
    id: uuid(),
    month: "April",
    gamesPurchased: 4,
  },
  {
    id: uuid(),
    month: "May",
    gamesPurchased: 7,
  },
  {
    id: uuid(),
    month: "June",
    gamesPurchased: 1,
  },
];

export const categories: CategoriesType[] = [
  {
    id: uuid(),
    title: "Action",
    backgroundImg: bg1,
    icon: categoryAction,
    genre: "action",
  },
  {
    id: uuid(),
    title: "Sport",
    backgroundImg: bg3,
    icon: categorySport,
    genre: "sport",
  },
  {
    id: uuid(),
    title: "Strategy",
    backgroundImg: bg2,
    icon: categoryStrategy,
    genre: "strategy",
  },
  {
    id: uuid(),
    title: "Horror",
    backgroundImg: bg4,
    icon: categoryHorror,
    genre: "horror",
  },
];

export const privacy: PrivacyType = {
  title: "Gamer - privacy policy",
  description: `We give a lot of importance to the protection of your data. We have established safety and confidential rules to ensure the best possible protection of your data. We do, however, need to collect certain information when you order. Please know that personal data is not collected without your prior consent. These rules apply to all those involved with the company.`,
  part1: "1. About us",
  part1text:
    "This website and lists various digital content, e.g. downloadable game titles and other downloadable content (“Content”). We sell on the website official keys, issued by the publisher and/or the developer of relevant Content (“Developer”), which allow the user to unlock, access and download the relevant Content from the Developer platforms (“Code(s)”). We are not the Developer of the Content and we do not own or operate the Developer platforms.",
  part2: "2. Who does this privacy notice apply to?",
  part2text: `This privacy notice applies to individuals who access, browse and use our website. Its aim is to give you information on how we collect and process your personal data through your use of the website. We collect personal data when you access our website, register with us, contact us, send us feedback and product reviews, purchase Codes and other products via our website, post material to our website, request marketing updates and take part in promotions, surveys, affiliation or partnership programs via our website.`,
  part3: "3. Third party links",
  part3text: `The website may include links to third party websites, plug-ins and applications. Clicking on those links or enabling those connections may allow third parties to collect or share data about you. We do not control these third party websites and are not responsible for their privacy notices. When you leave our website, we encourage you to read the privacy notices of every website you visit. Please see our cookies policy for details of cookies and similar technologies served by third parties and how to control these.`,
  part4: "4. International transfers",
  part4text: `We are located in Slovakia and so your personal data will be received and processed by us in Slovakia. It may be necessary for us to disclose some of your personal data to our trusted suppliers who provide us with products and services that assist us in providing our services to you. Our trusted suppliers are located inside the European Economic Area. We will ensure that any international transfers of your personal data are in accordance with applicable laws.`,
  part5: "5. Data security",
  part5text: `We have security measures in place to prevent personal data from being accidentally lost or used or accessed in an unauthorised way. We limit access to your personal data to those who have a genuine business need to know it. Those processing your personal data will do so only in an authorised manner and are subject to obligations of confidentiality. You recognise that no entity can keep personal data fully secure. If you have reason to believe that any of your personal data is no longer secure, please notify us immediately by contacting us using the information provided in section 13 below.`,
  part6: "6. Contact us",
  part6text: `If you have any questions about this privacy notice, including any requests to exercise your legal rights, please contact us through the support and contact us links on the website or by logging into your user account and log. `,
  part7: "7. Changes to this privacy notice",
  part7text: `We will change this privacy notice from time to time and any changes will be contained in a revised privacy notice posted on the website. This version of the privacy notice was last updated on 1st June 2023 and historic versions can be obtained by contacting us.`,
};

export const terms: TermsType = {
  title: "Gamer - general terms of sale",
  part1: "1. Who we are?",
  part1text: `Our Website lists various digital content, e.g. downloadable game titles and other downloadable content (“Content”). We sell on the Website official keys, issued by the publisher and/or the developer of relevant Content (“Developer”), which allow the user to unlock, access and download the relevant Content from the Developers platform (“Code(s)”). We are not the Developer of the Content and we do not own or operate the Developer’s platform. In addition to these Terms, you may also be subject to the Developers end user licence agreement and other terms related to its Content and its platform.`,
  part2: "2. How to contact us",
  part2text: `You can contact us through the support and contact us links on the Website or by logging into your User Account and logging a customer support request or ticket.`,
  part3: "3. About you",
  part3text: `In order for you to buy Codes from us through the Website you need to have a valid user account for the Website (“User Account”), have a valid payment method that we accept, be authorised to use that payment method (e.g. it is in your name or you have the right to use it) and a mobile, computer, television, watch or other supported device (“Device”) that is capable of accessing and downloading the Content. You must keep your User Account details secure and must not share them with anyone else.`,
  part4: "4. Your privacy and personal data",
  part4text: `Any personal data that you provide to us will be dealt with in accordance with our Privacy Notice, which explains what personal data we collect from you, how and why we collect, store, use and share such information and your rights in relation to your personal data.`,
  part5: "5. Price and payment",
  part5text: ` Where to find the price for Codes. The price payable for Codes is the price displayed in conjunction with the particular Content on the order pages when you place your order. The price for Codes will generally default to the national currency for the location from which you access the Website. You may select an alternative currency from the options made available on the Website. In which case, the price for Codes will be displayed and paid in your chosen currency. If VAT is payable on our sale of Codes the price we display will include VAT at the applicable rate. Prices do not include the cost of mobile data or any other costs charged by your mobile communications provider. Pricing and availability of all Codes displayed through the Website are subject to change at any time prior to purchase.`,
  part6: "6. Update to these Terms",
  part6text: `We may amend these Terms from time to time. Please check these Terms each time you order Codes to ensure you agree with the Terms that apply at that time, as any such new Terms will apply to all subsequent purchases. Any changes to these Terms made after our acceptance of your order will not affect your order.`,
};
